Fix broken link to paper from Modelica Conference
modelica-3rdparty/PowerSystems pull request #47
Opened 2022-03-28 09:40 UTC by GallLeo

See diff.

2022-03-28 10:48 UTC, dietmarw requested changes

2022-03-28 10:48 UTC, dietmarw commented on README.md
> +See also the publication [Franke, Wiesmann: Flexible modeling of electrical power systems - the Modelica PowerSystems library, Modelica conference 2014](https://ep.liu.se/ecp/096/054/ecp14096054.pdf)
```suggestion
See also the publication [Franke, Wiesmann: Flexible modeling of electrical power systems - the Modelica PowerSystems library, Modelica conference 2014](https://doi.org/10.3384/ECP14096515).
```

2022-03-28 10:48 UTC, dietmarw commented on README.md
> +See also the publication [Franke, Wiesmann: Flexible modeling of electrical power systems - the Modelica PowerSystems library, Modelica conference 2014](https://ep.liu.se/ecp/096/054/ecp14096054.pdf)
I think it is even more future-proof to use DOI links instead.

2022-06-19 16:27 UTC, merged

2022-06-19 16:27 UTC, rfranke commented
Thank you for the fix!